# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_R8A7795) += r8a7795-salvator-4x2g-overlay.dtb
dtb-$(CONFIG_ARCH_R8A7795) += r8a7795-h3ulcb-4x2g-overlay.dtb
dtb-$(CONFIG_ARCH_R8A7795) += r8a7795v2-h3ulcb-kf-overlay.dtb
dtb-$(CONFIG_ARCH_R8A7795) += r8a7795v2-salvator-overlay.dtb
dtb-$(CONFIG_ARCH_R8A7795) += r8a7795v3-h3ulcb-kf-overlay.dtb
dtb-$(CONFIG_ARCH_R8A7795) += r8a7795v3-salvator-overlay.dtb
dtb-$(CONFIG_ARCH_R8A7795) += ulcb-kf-adsp-overlay.dtb
dtb-$(CONFIG_ARCH_R8A7795) += salvator-adsp-overlay.dtb
dtb-$(CONFIG_ARCH_R8A7795) += lvds-AA104XD12-overlay.dtb
dtb-$(CONFIG_ARCH_R8A7795) += lvds-AA121TD01-overlay.dtb
dtb-$(CONFIG_ARCH_R8A7795) += lvds-TX31D200VM0BAA-overlay.dtb
dtb-$(CONFIG_ARCH_R8A7796) += lvds-AA104XD12-overlay.dtb
dtb-$(CONFIG_ARCH_R8A7796) += lvds-AA121TD01-overlay.dtb
dtb-$(CONFIG_ARCH_R8A7796) += lvds-TX31D200VM0BAA-overlay.dtb
dtb-$(CONFIG_ARCH_R8A77965) += lvds-AA104XD12-overlay.dtb
dtb-$(CONFIG_ARCH_R8A77965) += lvds-AA121TD01-overlay.dtb
dtb-$(CONFIG_ARCH_R8A77965) += lvds-TX31D200VM0BAA-overlay.dtb

always		:= $(dtb-y)
