# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_R8A7795) += android-h3-salvator-x.dtb
dtb-$(CONFIG_ARCH_R8A7795) += android-h3-salvator-xs.dtb
dtb-$(CONFIG_ARCH_R8A7795) += android-h3-salvator-xs-2x2g.dtb
dtb-$(CONFIG_ARCH_R8A7795) += android-h3ulcb.dtb
dtb-$(CONFIG_ARCH_R8A7795) += android-h3ulcb-4x2g.dtb
dtb-$(CONFIG_ARCH_R8A7795) += android-h3-kingfisher.dtb
dtb-$(CONFIG_ARCH_R8A7795) += android-h3-kingfisher-4x2g.dtb
dtb-$(CONFIG_ARCH_R8A7796) += android-m3-salvator-x.dtb
dtb-$(CONFIG_ARCH_R8A7796) += android-m3-salvator-xs.dtb
dtb-$(CONFIG_ARCH_R8A77965) += android-m3n-salvator-xs.dtb

always		:= $(dtb-y)
